name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on commits to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Clean up previous files
        run: |
          rm -rf *

      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
         
      - name: Install backend dependencies
        run: |
          cd server
          npm install
       #  npm install --save-dev jest

      - name: Install frontend dependencies
        run: |
          cd client
          npm install
  
      - name: Run tests
        run: |
          cd server
          npm test
  
      - name: Build frontend
        run: |
          cd client
          npm run build

   #   - name: configure AWS credentials
   #     uses: aws-actions/configure-aws-credentials@v1
   #     with:
   #      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
   #      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
   #      aws-region: ap-south-1

   
      - name: list all files
        run: |
          
          ls -R
      
      - name: Deploy to AWS EC2
        run: |
          chmod +x deploy.sh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" >> private-key.pem
          chmod 600 private-key.pem
          ./deploy.sh private-key.pem ${{ secrets.EC2_PUBLIC_IP }}
      
          
